### PR TITLE
Automated cherry pick of #22: fix image building

### PR DESCRIPTION
**Pull request by Brian-McM**
Cherry pick of #22 on release-v1.1.

#22: fix image building

### CODE REVIEW

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and delete the branch after I've merged it.

**Review by doublek — APPROVED** [review]
⛏️ LGTM

**Comment by marvin-tigera** [comment]
I'm sorry but I failed delete the branch after merging the pull request.

**Pull request merged**
